name: tubes_ui
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.12
  font_awesome_flutter: ^9.2.0
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  provider: ^6.0.0
  shared_preferences: any
  intl: ^0.17.0
  fluttertoast: ^8.2.2
  flutter_slidable: ^0.6.0
  mobile_scanner: ^3.2.0
  path: any
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  audioplayers: ^5.2.0
  pdf: ^3.6.4
  printing: ^5.9.0
  image_picker: ^1.0.4
  barcode_widget: ^2.0.4
  uuid: ^3.0.6
  responsive_sizer: ^3.2.0
  flutter_svg: ^2.0.9 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf

  assets:
    - assets/images/gojohh.jpg
    - assets/images/promo.jpeg
    - assets/images/car1.jpeg
    - assets/images/splash.jpg
    - assets/images/checkmark.png
    - assets/images/free.png
    - assets/flags/US.png
    - assets/flags/ID.png
    - assets/flags/JP.png
    - assets/flags/CN.png
  uses-material-design: true
